from __future__ import annotations
from typing import Any, Dict, Optional
import os
import httpx
import pandas as pd

def run(input_data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    input_data = input_data or {}
    
    try:
        # Fetch historical financial data from API (e.g. Quandl or Alpha Vantage)
        api_key: str      = os.getenv("QUANDL_API_KEY", "")
        url: str           = "https://www.quandl.com/api/v3/datasets/WIKI/VNFIN.json"
        params: dict       = {"api_key": api_key, "start_date": "2020-01-01"}
        
        with httpx.Client(timeout=15) as client:
            resp = client.get(url, headers={"Authorization": f"Bearer {api_key}"}, params=params)
            resp.raise_for_status()
            data: dict = resp.json()
            
        # Apply custom business logic to calculate revenue growth
        df: pd.DataFrame = pd.DataFrame(data["dataset"]["data"])
        revenue_growth: float = (df.iloc[-1][2] - df.iloc[0][2]) / df.iloc[0][2]
        
        # Use smtplib to send email with analysis summary and detailed report attached
        from_email: str    = os.getenv("FROM_EMAIL", "")
        to_email: str      = os.getenv("TO_EMAIL", "")
        password: str      = os.getenv("PASSWORD", "")
        subject: str       = "VinFast Revenue Analysis"
        content: str       = f"Revenue growth rate: {revenue_growth:.2f}%\nDetailed report attached."
        
        # Extract base64 images generated by python code (charts/matplotlib)
        image_base64: str  = input_data.get("image_base64", "")
        
        if not all([from_email, to_email, password]):
            raise ValueError("Missing: FROM_EMAIL, TO_EMAIL, or PASSWORD")
        
        msg = EmailMessage()
        msg.set_content(content)
        msg["Subject"] = subject
        msg["From"]    = from_email
        msg["To"]      = to_email
        
        # Attach image via Base64 (from local chart generation)
        if image_base64:
            import base64
            img_b64 = image_base64
            # Strip data URI header if present
            if img_b64.startswith("data:image"):
                img_b64 = img_b64.split(",", 1)[1]
            try:
                img_data = base64.b64decode(img_b64)
                msg.add_attachment(img_data, maintype="image", subtype="png", filename="chart.png")
            except Exception as e:
                msg.set_content(str(msg.get_content()) + f"
[Lỗi hiển thị biểu đồ đính kèm: {e}]")
        
        # Automatically download and attach image if url is provided
        else:
            with httpx.Client(timeout=10) as client:
                res = client.get(input_data["image_url"])
                if res.status_code == 200:
                    image_data = res.content
                    maintype = "image"
                    subtype = "jpeg" # default
                    if "png" in input_data["image_url"].lower(): subtype = "png"
                    msg.add_attachment(image_data, maintype=maintype, subtype=subtype, filename=f"attachment.{subtype}")
        
        # Send Email
        with smtplib.SMTP_SSL(os.getenv("SMTP_HOST", ""), 465) as smtp:
            smtp.login(from_email, password)
            smtp.send_message(msg)
        
        return {
            "status": "success",
            "analysis_summary": f"Revenue growth rate: {revenue_growth:.2f}%",
            "summary": f"Email sent to {to_email}",
        }
    
    except Exception as exc:
        return {"status": "error", "data": {}, "summary": str(exc)}
